#!/bin/bash

python_executable="python3.10"

# autoflake
echo "Checking unused imports and variables with autoflake..."
CHECK="$python_executable -m autoflake --in-place"
python_files_to_check=$(git diff --cached --name-only --diff-filter=d | grep -E '\.(py)$' | tr '\n' ' ')

status=0
for file in $python_files_to_check; do
  committed_content=$(cat "$file")

  $CHECK "$file" || status=1

  if [ "$(cat "$file")" != "$committed_content" ]; then
    echo "Autoflake removed unused imports in $file."
    git add "$file"
  fi
done

if [ "$status" != 0 ]; then
  exit $status
fi

# black
echo "Checking code with black..."
CHECK="$python_executable -m black --diff --check --config=./pyproject.toml"

status=0
for file in $python_files_to_check; do
  $CHECK "$file" || status=1
done

if [ "$status" != 0 ]; then
  exit $status
fi

# isort
echo "Checking import order with isort..."
CHECK="$python_executable -m isort --diff --check --filter-files --settings-file=./pyproject.toml"

status=0
for file in $python_files_to_check; do
  $CHECK "$file" || status=1
done

if [ "$status" != 0 ]; then
  exit $status
fi