name: Checks

on: [ pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test apps
        run: |
          docker compose up -d postgres
          docker compose run --build --rm django python backend/manage.py test